In [160]:
import numpy as np
import pandas as pd
from pytrends.request import TrendReq

In [161]:
df = pd.read_csv('cleaned_wilfire_environmental_data.csv')

In [162]:
df.head()

,DiscoveryDate,DiscoveryDayOfYear,DiscoveryTime,ContainmentDate,ContainmentDayOfYear,ContainmentTime,FireSize,FireSizeClass,Latitude,Longitude,CauseClassification,GeneralCause,MinTemperature,MaxTemperature,AvgTemperature,Precipitation,Snowfall
0,1992-01-01,1,01:30,1992-01-01,1.0,02:10,0.1,A,38.205000,-120.335000,Natural,Natural,3.89,13.89,8.89,0.0,0.0
1,1992-01-01,1,13:30,1992-01-01,1.0,17:00,5.0,B,33.166700,-116.634200,Human,Debris and open burning,-1.67,12.78,5.56,0.0,0.0
2,1992-01-01,1,14:37,1992-01-01,1.0,15:07,0.2,A,33.663889,-116.171944,Human,Misuse of fire by a minor,-1.67,12.78,5.56,0.0,0.0
3,1992-01-02,2,14:37,1992-01-02,2.0,15:07,0.2,A,33.030000,-116.831944,Human,Missing data/not specified/undetermined,-1.11,12.22,5.56,0.0,0.0
4,1992-01-02,2,14:37,1992-01-02,2.0,15:17,0.5,B,33.896111,-116.990000,Human,Missing data/not specified/undetermined,-1.11,12.22,5.56,0.0,0.0

In [163]:
# Split data into pre-2004 and post-2004
pre_df = df[df['DiscoveryDate'] < '2004-01-01']
post_df = df[df['DiscoveryDate'] >= '2004-01-01']
pre_df

,DiscoveryDate,DiscoveryDayOfYear,DiscoveryTime,ContainmentDate,ContainmentDayOfYear,ContainmentTime,FireSize,FireSizeClass,Latitude,Longitude,CauseClassification,GeneralCause,MinTemperature,MaxTemperature,AvgTemperature,Precipitation,Snowfall
0,1992-01-01,1,01:30,1992-01-01,1.0,02:10,0.1,A,38.205000,-120.335000,Natural,Natural,3.89,13.89,8.89,0.00,0.0
1,1992-01-01,1,13:30,1992-01-01,1.0,17:00,5.0,B,33.166700,-116.634200,Human,Debris and open burning,-1.67,12.78,5.56,0.00,0.0
2,1992-01-01,1,14:37,1992-01-01,1.0,15:07,0.2,A,33.663889,-116.171944,Human,Misuse of fire by a minor,-1.67,12.78,5.56,0.00,0.0
3,1992-01-02,2,14:37,1992-01-02,2.0,15:07,0.2,A,33.030000,-116.831944,Human,Missing data/not specified/undetermined,-1.11,12.22,5.56,0.00,0.0
4,1992-01-02,2,14:37,1992-01-02,2.0,15:17,0.5,B,33.896111,-116.990000,Human,Missing data/not specified/undetermined,-1.11,12.22,5.56,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96831,2003-12-29,363,07:41,2003-12-29,363.0,08:00,0.1,A,34.140000,-117.150000,Human,Power generation/transmission/distribution,-1.67,9.44,3.89,0.00,0.0
96832,2003-12-29,363,21:40,2003-12-29,363.0,22:30,0.1,A,34.381944,-118.097222,Human,Arson/incendiarism,-1.67,9.44,3.89,0.00,0.0
96833,2003-12-31,365,15:58,2003-12-31,365.0,16:31,0.2,A,33.968056,-117.515000,Human,Equipment and vehicle use,0.56,12.78,6.67,0.00,0.0
96834,2003-12-31,365,16:53,2003-12-31,365.0,17:02,0.1,A,38.185000,-120.371389,Human,Debris and open burning,3.89,11.11,7.50,0.51,0.0
96835,2003-12-31,365,18:05,2003-12-31,365.0,18:25,0.1,A,32.933400,-115.134100,Human,Recreation and ceremony,0.56,12.78,6.67,0.00,0.0

In [164]:
post_df.reset_index(drop=True, inplace=True)
post_df

,DiscoveryDate,DiscoveryDayOfYear,DiscoveryTime,ContainmentDate,ContainmentDayOfYear,ContainmentTime,FireSize,FireSizeClass,Latitude,Longitude,CauseClassification,GeneralCause,MinTemperature,MaxTemperature,AvgTemperature,Precipitation,Snowfall
0,2004-01-01,1,15:00,2004-01-01,1.0,15:30,0.1,A,32.691755,-116.902617,Human,Arson/incendiarism,0.00,12.78,6.39,0.00,0.0
1,2004-01-02,2,12:05,2004-01-02,2.0,12:15,0.1,A,32.997800,-115.083900,Natural,Natural,7.22,12.78,10.00,0.00,0.0
2,2004-01-02,2,18:00,2004-01-02,2.0,18:30,0.1,A,32.722625,-116.830936,Human,Missing data/not specified/undetermined,7.22,12.78,10.00,0.00,0.0
3,2004-01-03,3,12:05,2004-01-03,3.0,12:15,0.1,A,34.346389,-118.363611,Human,Arson/incendiarism,1.11,11.67,6.39,0.00,0.0
4,2004-01-03,3,20:15,2004-01-03,3.0,20:50,0.1,A,32.981700,-115.061100,Human,Recreation and ceremony,1.11,11.67,6.39,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150885,2020-12-31,366,16:58,2020-12-31,366.0,18:41,15.8,C,38.938853,-121.107672,Human,Debris and open burning,-1.11,10.00,4.44,19.81,0.0
150886,2020-12-31,366,17:43,2020-12-31,366.0,18:23,0.5,B,34.073641,-117.787055,Human,Debris and open burning,2.22,15.56,8.89,0.00,0.0
150887,2020-12-31,366,20:32,2020-12-31,366.0,21:02,0.1,A,33.982775,-117.234942,Missing data/not specified/undetermined,Missing data/not specified/undetermined,2.22,15.56,8.89,0.00,0.0
150888,2020-12-31,366,22:21,2020-12-31,366.0,22:51,0.1,A,33.704975,-117.207482,Missing data/not specified/undetermined,Missing data/not specified/undetermined,2.22,15.56,8.89,0.00,0.0
150889,2020-12-31,366,23:36,2020-12-31,366.0,00:06,0.2,A,38.245282,-122.069806,Missing data/not specified/undetermined,Missing data/not specified/undetermined,-1.11,10.00,4.44,19.81,0.0

In [165]:
df.columns

Index(['DiscoveryDate', 'DiscoveryDayOfYear', 'DiscoveryTime',
       'ContainmentDate', 'ContainmentDayOfYear', 'ContainmentTime',
       'FireSize', 'FireSizeClass', 'Latitude', 'Longitude',
       'CauseClassification', 'GeneralCause', 'MinTemperature',
       'MaxTemperature', 'AvgTemperature', 'Precipitation', 'Snowfall'],
      dtype='object')

In [166]:
# Define the start and end dates
start_date = pd.to_datetime('2004-01-01')
end_date = pd.to_datetime('2020-12-31')

timeframe_list = []

# Add 8-month intervals to get daily trend data
current_date = start_date
while current_date < end_date:
    next_date = current_date + pd.DateOffset(months=8) - pd.Timedelta(days=1)
    
    if next_date > end_date:
        next_date = end_date  
    
    timeframe_list.append(f'{current_date.strftime("%Y-%m-%d")} {next_date.strftime("%Y-%m-%d")}')
    current_date = next_date + pd.Timedelta(days=1)

timeframe_list

['2004-01-01 2004-08-31',
 '2004-09-01 2005-04-30',
 '2005-05-01 2005-12-31',
 '2006-01-01 2006-08-31',
 '2006-09-01 2007-04-30',
 '2007-05-01 2007-12-31',
 '2008-01-01 2008-08-31',
 '2008-09-01 2009-04-30',
 '2009-05-01 2009-12-31',
 '2010-01-01 2010-08-31',
 '2010-09-01 2011-04-30',
 '2011-05-01 2011-12-31',
 '2012-01-01 2012-08-31',
 '2012-09-01 2013-04-30',
 '2013-05-01 2013-12-31',
 '2014-01-01 2014-08-31',
 '2014-09-01 2015-04-30',
 '2015-05-01 2015-12-31',
 '2016-01-01 2016-08-31',
 '2016-09-01 2017-04-30',
 '2017-05-01 2017-12-31',
 '2018-01-01 2018-08-31',
 '2018-09-01 2019-04-30',
 '2019-05-01 2019-12-31',
 '2020-01-01 2020-08-31',
 '2020-09-01 2020-12-31']

In [167]:
# Initialize pytrends request
pytrends = TrendReq(hl="en-US", tz=360)
search_terms = ['wildfire', 'forest fire', 'california fire', 'fire season', 'fire prevention']


# fetch google trend data
all_trend_data = []

for timeframe in timeframe_list:
    pytrends.build_payload(search_terms, timeframe=timeframe, geo='US-CA')
    data = pytrends.interest_over_time()
    
    # drop inPartial column if exists
    if 'isPartial' in data.columns:
        data = data.drop(columns=['isPartial'])
        
        all_trend_data.append(data)

# Concatenate all data
trend_data = pd.concat(all_trend_data)
trend_data.reset_index(inplace=True)
trend_data

,date,wildfire,forest fire,california fire,fire season,fire prevention
0,2004-01-01,0,0,0,0,0
1,2004-01-02,0,0,0,0,0
2,2004-01-03,0,0,0,0,0
3,2004-01-04,0,0,0,0,0
4,2004-01-05,0,0,0,0,0
...,...,...,...,...,...,...
6205,2020-12-27,0,0,1,0,0
6206,2020-12-28,1,0,1,1,0
6207,2020-12-29,1,0,1,0,0
6208,2020-12-30,0,0,1,1,0
6209,2020-12-31,0,0,1,0,0

In [168]:
trend_data['GoogleTrendAverage'] = trend_data[['wildfire','forest fire','california fire','fire season','fire prevention']].mean(axis=1)
trend_data

,date,wildfire,forest fire,california fire,fire season,fire prevention,GoogleTrendAverage
0,2004-01-01,0,0,0,0,0,0.0
1,2004-01-02,0,0,0,0,0,0.0
2,2004-01-03,0,0,0,0,0,0.0
3,2004-01-04,0,0,0,0,0,0.0
4,2004-01-05,0,0,0,0,0,0.0
...,...,...,...,...,...,...,...
6205,2020-12-27,0,0,1,0,0,0.2
6206,2020-12-28,1,0,1,1,0,0.6
6207,2020-12-29,1,0,1,0,0,0.4
6208,2020-12-30,0,0,1,1,0,0.4
6209,2020-12-31,0,0,1,0,0,0.2

In [169]:
# Merge google trend average and post 2004 wildfire data
post_df = post_df.copy()
trend_data['date'] = pd.to_datetime(trend_data['date'])
post_df['DiscoveryDate'] = pd.to_datetime(post_df['DiscoveryDate'])
merged_post_df = pd.merge(post_df, trend_data[['date', 'GoogleTrendAverage']], left_on='DiscoveryDate', right_on='date', how='left')
merged_post_df.drop(columns=['date'], inplace=True)

In [170]:
merged_post_df

,DiscoveryDate,DiscoveryDayOfYear,DiscoveryTime,ContainmentDate,ContainmentDayOfYear,ContainmentTime,FireSize,FireSizeClass,Latitude,Longitude,CauseClassification,GeneralCause,MinTemperature,MaxTemperature,AvgTemperature,Precipitation,Snowfall,GoogleTrendAverage
0,2004-01-01,1,15:00,2004-01-01,1.0,15:30,0.1,A,32.691755,-116.902617,Human,Arson/incendiarism,0.00,12.78,6.39,0.00,0.0,0.0
1,2004-01-02,2,12:05,2004-01-02,2.0,12:15,0.1,A,32.997800,-115.083900,Natural,Natural,7.22,12.78,10.00,0.00,0.0,0.0
2,2004-01-02,2,18:00,2004-01-02,2.0,18:30,0.1,A,32.722625,-116.830936,Human,Missing data/not specified/undetermined,7.22,12.78,10.00,0.00,0.0,0.0
3,2004-01-03,3,12:05,2004-01-03,3.0,12:15,0.1,A,34.346389,-118.363611,Human,Arson/incendiarism,1.11,11.67,6.39,0.00,0.0,0.0
4,2004-01-03,3,20:15,2004-01-03,3.0,20:50,0.1,A,32.981700,-115.061100,Human,Recreation and ceremony,1.11,11.67,6.39,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150885,2020-12-31,366,16:58,2020-12-31,366.0,18:41,15.8,C,38.938853,-121.107672,Human,Debris and open burning,-1.11,10.00,4.44,19.81,0.0,0.2
150886,2020-12-31,366,17:43,2020-12-31,366.0,18:23,0.5,B,34.073641,-117.787055,Human,Debris and open burning,2.22,15.56,8.89,0.00,0.0,0.2
150887,2020-12-31,366,20:32,2020-12-31,366.0,21:02,0.1,A,33.982775,-117.234942,Missing data/not specified/undetermined,Missing data/not specified/undetermined,2.22,15.56,8.89,0.00,0.0,0.2
150888,2020-12-31,366,22:21,2020-12-31,366.0,22:51,0.1,A,33.704975,-117.207482,Missing data/not specified/undetermined,Missing data/not specified/undetermined,2.22,15.56,8.89,0.00,0.0,0.2
150889,2020-12-31,366,23:36,2020-12-31,366.0,00:06,0.2,A,38.245282,-122.069806,Missing data/not specified/undetermined,Missing data/not specified/undetermined,-1.11,10.00,4.44,19.81,0.0,0.2

In [171]:
merged_post_df['GoogleTrendAverage'].isna().sum()

0

In [172]:
pre_df.to_csv('pre_2004_data.csv', index=False)
merged_post_df.to_csv('post_2004_data_with_google_trend.csv', index=False)